# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(help_text='"Nothing is true, everything is permitted."', max_length=1023, verbose_name='Group description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='displayed_to',
            field=models.CharField(help_text='Multiple groups must be separated with line-breaks, i.e. one group per line!', max_length=1023, verbose_name='Displayed to this group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='We do not support changing the name of a group after creation!', max_length=255, unique=True, verbose_name='Group name'),
        ),
    ]
