# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20170125_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='displayed_to',
            field=models.CharField(help_text='Multiple groups must be separated with \\n!', max_length=1023, verbose_name='Displayed to this group'),
        ),
    ]
